# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target ‘Red’ do
  #pod 'Parse'
  pod 'AFNetworking', '~> 2.0'
  pod 'SDWebImage', '~> 3.6'
  pod 'pop', '~> 1.0'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'IOSLinkedInAPI', :git => 'https://github.com/jeyben/IOSLinkedInAPI', :commit => '7b777b16867c713ed660c1d3711f83b76388ea99'
  pod 'Parse'
  pod 'ParseUI'
  pod 'ParseFacebookUtilsV4'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end